import type { NextPage, NextPageContext } from "next";
import { useState } from "react";
import Head from "next/head";
import Filters from "../components/Filters";
import Members from "../components/members/Members";
import Navbar from "../components/layout/Navbar";

const Home: NextPage = () => {
  const [members, setMembers] = useState([
    {
      id: 1,
      name: "Julius",
      age: 27,
      rating: 5,
      activities: ["fishing", "hunting", "archery", "biking"],
    },
    {
      id: 2,
      name: "John",
      age: 37,
      rating: 7,
      activities: ["hiking", "hunting", "archery", "swimming"],
    },
    {
      id: 3,
      name: "Emma",
      age: 17,
      rating: 10,
      activities: ["archery", "swimming", "running", "hiking"],
    },
  ]);
  const [searchString, setSearchString] = useState("");
  const numHikers = members.filter((mem: any) => {
    return mem.activities.includes("hiking");
  });
  const numRunners = members.filter((mem: any) => {
    return mem.activities.includes("running");
  });
  const numBikers = members.filter((mem: any) => {
    return mem.activities.includes("biking");
  });
  return (
    <>
      <Head>
        <title>Outdoor Adventure Club | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        searchString={searchString}
        setSearchString={setSearchString}
        members={members}
        setMembers={setMembers}
      />
      <Members
        members={members}
        setMembers={setMembers}
        searchString={searchString}
      />
      <p>There are {numHikers.length} people hiking</p>
      <p>There are {numRunners.length} people running</p>
      <p>There are {numBikers.length} people biking</p>
    </>
  );
};

export default Home;
